version: "3.5"
    
networks:
    airflow: bridge
        
services: 
    python:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:3000"
        environment:
            - AIRFLOW_HOME=/opt/airflow
        volumes:
            - ./init.sh:/opt/init.sh
            - ./dags:/opt/airflow/dags
        networks:
            - python_network
        entrypoint: ['/opt/init.sh']
        
networks:
    python_network:
        driver: bridge
